version: '3.9'

services:
  # PostgreSQL Database Service
  db:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment: 
      POSTGRES_DB: blog
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  # Laravel Application Service
  app:
    container_name: laravel
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:80 # Exposes Laravel's internal server
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: blog
      DB_USERNAME: root
      DB_PASSWORD: password
   
  # Optional: pgAdmin for Database Management
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
